services:
  frontend:
    image: sigovia-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0
